# Generated by Django 4.2.1 on 2023-07-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_bio_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public_username',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=30),
        ),
    ]
