# Generated by Django 4.2.1 on 2023-07-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
    ]
